language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install
script:
- npm run build
branches:
  only:
  - master
after_success:
- npm run deploy
env:
  global:
  - secure: "l6Vl6tdsUbDABL7iZAhuJJQ50Od3Nu0J1jSbGZIkguq5KHCylAZ+64fEBHOvHwOnKTLrLJ91NfIbHWnlgZGLkO2jglCqmRfW0gLZwEEuFmXEpHdllqV1LbW3kztwaZh2xdZduoLu7uz8yQFFNTyC35ONZYeYzDPIRPDlFUVVUweK6XL6e0omoMZCcSFXbrXcS1TQKvwFyGoohUnLJ3d7lL31OCUnvaawZlpgZaaUZLCy33nq2Devsbzqg9CPIomOqEPYP/r3J5LdzMdPDLf3jblfhow3lis+MaFvpfzM6fCBhi13DvAD25MCWiuekllzrD4goUN/ll2t29l0SfczIMnFREIjXvXWETlzZgFaZu5ohdDbYFhDM3oCLNU+DgC0v7Zr41NES/KDGqQgmFA9a9GWsiOhxl0Ofl9LI6zvlCQtF0AoWDIVX2nUpPAn8tmWdvwKb45UpajLs7HF6RNehZIFucFDcv2uvNoWWZ6ORkM716hajLhBxf0CFA3JZzVIbS4lRHLlH0jqAl8LTzc+W/ix26c2PHNsFFBXR5a7mc/9PIHo8SMrYK4ZXspRFFT/jA6E48jcLrpyl3scXphhYUVIK0A9lXDgaF9GtUVzheHo6qnLEecQ1SUnanMf8G5LAdBZQllCkd03ysx4upEVWCFG6jjJfGsohbCgbCgOL6g="